import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        NEXEN PWA TEST
        <Link href={`/page1`}>
          <a>
            Pg1
          </a>
        </Link>
        <Link href={`/page2`}>
          <a>
            Pg2
          </a>
        </Link>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
